set_property SRC_FILE_INFO {cfile:/home/andy/Documents/ece_520/fa22-ece520-final-project-alopez099/hardware/color_dector/color_dector.srcs/constrs_1/new/master.xdc rfile:../../../color_dector.srcs/constrs_1/new/master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U14 [get_ports Pmod_out_0_pin7_io]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U15 [get_ports Pmod_out_0_pin8_io]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports Pmod_out_0_pin9_io]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V18 [get_ports Pmod_out_0_pin10_io]
